### ISSUE TITLE
Need to install pybind11 before diffcp

### ISSUE THREAD

**Issue by sbarratt** [cvxgrp/diffcp#15]
In a fresh virtual environment, when I run `pip install diffcp`
I get the error:
```bash
cpp/src/wrapper.cpp:1:10: fatal error: pybind11/eigen.h: No such file or directory
#include <pybind11/eigen.h>
         ^~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
----------------------------------------
ERROR: Failed building wheel for diffcp
```

Once I `pip install pybind11`, then `pip install diffcp` works perfectly fine.

This should just work though, because `pybind11` is in `setup_requires` in `setup.py`.

**Comment by sbarratt** [comment]
@akshayka

**Comment by akshayka** [comment]
Is this still broken? I was pretty sure my latest upload fixed this ...

**Comment by sbarratt** [comment]
still broken on both of my machines w/ fresh conda environments.

This seems to fix it though: https://github.com/cvxgrp/diffcp/pull/20
