### ISSUE TITLE
forward time not decreasing w/ as number of threads increases

### ISSUE THREAD

**Issue by sbarratt** [cvxgrp/diffcp#16]
When running `examples/batch.py` on my machine, I get the following output:

```bash
001 | 3.4388 +/- 0.00 | 0.4225 +/- 0.00
002 | 3.6921 +/- 0.00 | 0.3009 +/- 0.00
003 | 4.4002 +/- 0.00 | 0.2352 +/- 0.00
004 | 5.3111 +/- 0.00 | 0.1954 +/- 0.00
```

The leftmost column is the number of threads, the middle column is the time taken by the forward pass and the right is the time taken by the backward pass (using lsqr).

**Comment by akshayka** [comment]
Weirdly, my 2012 MB Pro doesn't exhibit this behavior

```
001 | 6.0815 +/- 0.00 | 0.6098 +/- 0.00
002 | 2.8611 +/- 0.00 | 0.2812 +/- 0.00
003 | 2.2086 +/- 0.00 | 0.2211 +/- 0.00
004 | 2.1439 +/- 0.00 | 0.2162 +/- 0.00
```

**Comment by bamos** [comment]
My system's doing:

```
001 | 6.5337 +/- 0.00 | 0.8536 +/- 0.00
002 | 4.9161 +/- 0.00 | 0.4410 +/- 0.00
003 | 6.1841 +/- 0.00 | 0.3583 +/- 0.00
004 | 6.8134 +/- 0.00 | 0.2580 +/- 0.00
```

**Comment by sbarratt** [comment]
We found the issue: https://github.com/cvxgrp/scs/blob/82df6213af31c87fccc23bc4e0b71b58a2cb7c9f/linsys/amatrix.c#L245

^There, openmp is being used to parallelize the for loop in `_accum_by_atrans`, which is using 6 threads and screwing up all parallelism from python. Removing those lines leads to the following numbers:
```bash
001 | 9.3322 +/- 0.00 | 0.4261 +/- 0.00
002 | 4.8056 +/- 0.00 | 0.2129 +/- 0.00
003 | 3.5702 +/- 0.00 | 0.1562 +/- 0.00
004 | 2.4217 +/- 0.00 | 0.1126 +/- 0.00
005 | 2.3912 +/- 0.00 | 0.1076 +/- 0.00
006 | 1.8532 +/- 0.00 | 0.0977 +/- 0.00
007 | 1.8748 +/- 0.00 | 0.0832 +/- 0.00
008 | 1.4279 +/- 0.00 | 0.0836 +/- 0.00
009 | 1.4054 +/- 0.00 | 0.0820 +/- 0.00
010 | 1.3801 +/- 0.00 | 0.0754 +/- 0.00
011 | 1.3974 +/- 0.00 | 0.0807 +/- 0.00
012 | 1.3999 +/- 0.00 | 0.0712 +/- 0.00
```

We should also probably remove the following line here: https://github.com/cvxgrp/scs/blob/7522ace00d582ed201461208567436ab9e72cabb/src/cones.c#L729

Steps moving forward:
Somehow we have to make sure that openmp is not used when installing scs.

**Comment by akshayka** [comment]
Not sure why Shane's version of SCS has OpenMP enabled; SCS makes OpenMP opt-in:

https://github.com/cvxgrp/scs/blob/e6ab81db115bb37502de0a9917041a0bc2ded313/scs.mk#L126

**Comment by bamos** [comment]
OMP inside of SCS can also be disabled by setting `OMP_NUM_THREADS=1`, which fixes this on my system too:

```
001 | 5.8294 +/- 0.00 | 0.7548 +/- 0.00
002 | 3.0185 +/- 0.00 | 0.4139 +/- 0.00
003 | 2.3057 +/- 0.00 | 0.3038 +/- 0.00
004 | 1.5876 +/- 0.00 | 0.2223 +/- 0.00
```

**Comment by bamos** [comment]
> Not sure why Shane's version of SCS has OpenMP enabled; SCS makes OpenMP opt-in:
> 
> https://github.com/cvxgrp/scs/blob/e6ab81db115bb37502de0a9917041a0bc2ded313/scs.mk#L126

`scs-python` pulls the source from the `scs` repo as a submodule and compiles it as an extension without using `scs.mk`, something here is probably enabling omp by default: https://github.com/bodono/scs-python/blob/master/setup.py#L137

**Comment by sbarratt** [comment]
I think this solves the problem: https://github.com/cvxgrp/diffcp/pull/17

**Comment by sbarratt** [comment]
> > Not sure why Shane's version of SCS has OpenMP enabled; SCS makes OpenMP opt-in:
> > https://github.com/cvxgrp/scs/blob/e6ab81db115bb37502de0a9917041a0bc2ded313/scs.mk#L126
> 
> `scs-python` pulls the source from the `scs` repo as a submodule and compiles it as an extension without using `scs.mk`, something here is probably enabling omp by default: https://github.com/bodono/scs-python/blob/master/setup.py#L137

We think maybe -lopenblas is linking openmp?

**Comment by sbarratt** [comment]
Maybe we could use this? https://github.com/joblib/threadpoolctl

**Comment by sbarratt** [comment]
Resolved by https://github.com/cvxgrp/diffcp/pull/17
