### ISSUE TITLE
ZeroDivisionError when SCS does not solve the problem

### ISSUE THREAD

**Issue by bstellato** [cvxgrp/diffcp#3]
I am getting a `ZeroDivisionError` for an instance where SCS returns primal infeasibility.

Here is a MWE
```python
import numpy as np
import cvxpy as cp
import diffcp
import pickle
import scs

with open("dump.pkl", "rb") as f:
    data = pickle.load(f)

A, b, c, cone_dict, dx = data['A'], data['b'], data['c'], data['cone_dict'], data['dx']
n = len(c)
m = len(b)


# Acceleration parameter
anderson = 10  # Diverges and returns infeasibility
#  anderson = 0  # Works

# Solve with CVXPY and OSQP
x = cp.Variable(n)
prob = cp.Problem(cp.Minimize(c * x), [A @ x <= b])
result_osqp = prob.solve(verbose=True)
x_osqp = x.value

# Compute derivatives with SCS
x, y, s, D, DT = diffcp.solve_and_derivative(A, b, c, cone_dict, verbose=True,
                                             acceleration_lookback=anderson)
dA, db, dc = DT(dx, np.zeros(m), np.zeros(m))  # ERROR
```

[dump.pkl.zip](https://github.com/cvxgrp/diffcp/files/3613197/dump.pkl.zip)

@bodono this is related to the Anderson acceleration in SCS. Lookback of 10 for this problem makes SCS diverge returning the wrong status. I had to disable the acceleration to make it work.

@akshayka @sbarratt I think this issue is in general related to what happens if the problem is not solved because of numerical issues or because it is infeasible. Have you thought about what kind of object or information to return in case the problem is infeasible?

**Comment by sbarratt** [comment]
We addressed this in https://github.com/cvxgrp/diffcp/pull/4.

In the future we plan to allow the user, if desired, to take derivatives of
problem data w.r.t. primal/dual infeasibility certificates.
However, we first need to work out the math.
