### ISSUE TITLE
Solver scs returned status Unbounded/Inaccurate

### ISSUE THREAD

**Issue by deepgradient** [cvxgrp/diffcp#32]
I occasionally face the following error when using the package for different matrices **A** and **b**.  It does not happen permanently, but I have no idea when it happens. It especially happens when I set sigma_value in the following code to less than `1e-4`

`

    def tf_solver(A: np.ndarray, b: np.ndarray, sigma_value: float):
   
        A = tf.constant(A)
        b = tf.constant(b)
        x_tf = cp.Variable((A.shape[1]))
        A_tf = cp.Parameter(A.shape)
        b_tf = cp.Parameter((b.shape[0]))

        constraints = [cp.norm(A_tf @ x_tf - b_tf, p=2) <= sigma_value]
        objective = cp.Minimize(cp.norm(x_tf, p=1))
        problem = cp.Problem(objective, constraints)

        assert problem.is_dpp()

        cvxpylayer = cvxlayer(problem, parameters=[A_tf, b_tf], variables=[x_tf])

        with tf.GradientTape() as tape:
            x, = cvxpylayer(A, b)
            summed_solution = tf.math.reduce_sum(x)

        gradA, gradb = tape.gradient(summed_solution, [A, b])
        grad = [gradA, gradb]

        residue = tf.tensordot(A, x, 1) - b

        return x.numpy(), grad, residue.numpy()

`

---------------------------------------------------------------------------------------------------------------------------------
<ipython-input-37-2022279bee48> 69 cs_procedure
x, grad, residue = tf_solver(A=precond_bi_orthonormal_matrix, b=precond_func_sampling_vector, sigma_value=sigma_value)
csUtils.py 30 tf_solver
x, = cvxpylayer(A, b)
cvxpylayer.py 109 __call__
return compute(*parameters)
custom_gradient.py 258 __call__
return self._d(self._f, a, k)
custom_gradient.py 212 decorated
return _eager_mode_decorator(wrapped, args, kwargs)
custom_gradient.py 409 _eager_mode_decorator
result, grad_fn = f(*args, **kwargs)
cvxpylayer.py 108 <lambda>
lambda *parameters: self._compute(parameters, solver_args))
cvxpylayer.py 160 _compute
A=A, b=b, c=c, cone_dict=self.cones, **solver_args)
cone_program.py 212 solve_and_derivative
A, b, c, cone_dict, warm_start=warm_start, mode=mode, **kwargs)
cone_program.py 262 solve_and_derivative_internal
raise SolverError("Solver scs returned status %s" % status)
diffcp.cone_program.SolverError:
Solver scs returned status Unbounded/Inaccurate

**Comment by akshayka** [comment]
I'm closing this issue because we're discussing it in the `diffcp` repo.
